### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by crutchcorn** [crutchcorn/DriverDownloader#1]
- [ ] Better error handling for `wget` function
- [x] Properly document Plugin system
- [x] Proper requirements.txt
- [ ] Option to delete or rename existing file
- [ ] Continue to add "ALT" until no longer possible
- [ ] Add option to rename duplications manually
- [ ] Use docopt for command line functionality
- [x] Implament plugin support (Lenovo plugin already grabs `drivers[]` properly)
- [ ] Fix strings with `,` in the name (in Lenovo plugin)
- [x] Pass arguments (URL, namely) to plugin
- [x] Automatically parse URL argument and run respective plugin
- [ ] Handle many downloads of drivers
- [ ] Split off different instances of driver downloads to proper directory tree
- [ ] Turn all regex stuff into some sort of library for easy lifting for others
- [ ] Add architechture support for driverpacksolution plugin
- [ ] Have wget not rename files if no "Name" is presented
